# Kubernetes Deployment Manifest and Service to create a two-replica deployment of a docker image 
# I build on my docker hub, called "italoleitecg/grafana-italo" containing a single container 
# listening on port 3000, exposed as a service of type NodePort on port 30000. I will use k3d's 
# port bind to redirect traffic to the application running on port 80 on the host machine.
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:  
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: italoleitecg/grafana-italo
        ports: 
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30000
  type: NodePort